### ISSUE TITLE
constructor

### ISSUE THREAD

**Issue by landsman** [martinknor/feed#1]
Ahoj,

jak do feedu dostanu závislost na mém modelu?
Potřebuji tam předat model z doctrine. Zkoušel jsem @inject ale nefungoval a vytvoření vlastního konstruktoru způsobilo spoustu potíží.

díky.

**Comment by martinknor** [comment]
Ahoj, nejlepe si vytvoris vzdy vlastni generator, a tam si v constructoru muzes predat co chces - pres autowire.

**Comment by landsman** [comment]
Vlastní generator?
Ten tvůj dědí ale od BaseGenerator, což bych defakto měl udělat také.

Není tady způsob, jak to dostat do toho tvého sample?
![snimek obrazovky 2016-11-27 v 21 51 04](https://cloud.githubusercontent.com/assets/3184228/20651782/962aa08e-b4eb-11e6-80ea-91f8588ea70e.png)

**Comment by martinknor** [comment]
Defakto tohle je treba z realne apky, do constructoru si das cokoliv potrebujes.

```php namespace Models\Feed\Zbozi;

use App\Components\CategoryTree;
use Carrooi\ImagesManager\ImagesManager;
use Entity\Category;
use Entity\Product;
use Mk\Feed\Generators\Zbozi\ExtraMessage;
use Mk\Feed\Generators\Zbozi\Item;
use Mk\Feed\Storage;
use Nette\Application\LinkGenerator;
/**
 * Class Generator
 * @author Martin Knor <martin.knor@gmail.com>
 * @package Models\Feed\Zbozi
 */
class Generator extends \Mk\Feed\Generators\Zbozi\Generator {
    /** @var \ProductRepository */
    private $productRepository;
    /** @var \Mk\Feed\Storage */
    private $storage;
    /** @var \Nette\Application\LinkGenerator */
    private $linkGenerator;
    /** @var \Carrooi\ImagesManager\ImagesManager */
    private $imagesManager;
    /** @var \App\Components\CategoryTree */
    private $categoryTree;

    /**
     * Generator constructor.
     * @param \Mk\Feed\Storage $storage
     * @param \ProductRepository $productRepository
     * @param \Nette\Application\LinkGenerator $linkGenerator
     * @param \Carrooi\ImagesManager\ImagesManager $imagesManager
     * @param \App\Components\CategoryTree $categoryTree
     */
    public function __construct(Storage $storage, \ProductRepository $productRepository, LinkGenerator $linkGenerator, ImagesManager $imagesManager, CategoryTree $categoryTree)
    {
        parent::__construct($storage);

        $this->productRepository = $productRepository;
        $this->storage = $storage;
        $this->linkGenerator = $linkGenerator;
        $this->imagesManager = $imagesManager;
        $this->categoryTree = $categoryTree;
    }
```

**Comment by landsman** [comment]
Paráda, díky, blbě jsem asi volal ten parent.

**Comment by martinknor** [comment]
Neni zac :)

**Comment by landsman** [comment]
Ještě se zeptám, nemáš tam nějaký ladící mód? 
Dělat var_dump na DB result a číst to v konzoli není příliš pohodlné.

**Comment by martinknor** [comment]
Nic takoveho tam bohuzel neni, to je jen pomocnik jak to pohodlne sestavit, takze defakto data jsou na tobe

**Comment by landsman** [comment]
Rozumím, takže si to dumpnout někde bokem v presenteru.

**Comment by landsman** [comment]
Jakým způsobem prosím generuješ absolutní odkazy? Nějak jsem si zvykl na makro v latte a teď to nemohu dohledat. Mám tam nyní: 
`->setUrl($this->linkGenerator->link("Catalog:Homepage:item", ["id" => $product->getId(), "slug" => $product->getSlug()]))`

**Comment by martinknor** [comment]
Pokud vim tak link generator generuje vzdy absolutni odkazy ne? Ja je generuju stejne a mam tam absolutni

**Comment by landsman** [comment]
Mě to právě připadalo divné. Vygeneruje mi relativní.
