### ISSUE TITLE
Problém s ukládáním většího feedu

### ISSUE THREAD

**Issue by jAKErCZ** [martinknor/feed#10]
Zdravím,
mám problém že při ukládání většího feedu s více produkty my componenta háže:
`PHP Warning:  DOMDocument::loadXML(): internal error: Huge input lookup in Entity, line: 845125`

Ale tohle hází jen u ukládání heureka.xml 

Zbozi.xml se v pořádku vyexportuje...

Jak tento problém mohu vyřešit?

**Comment by martinknor** [comment]
Zvetsit memory limit.

Dne pá 11. kvě 2018 11:42 uživatel Dominik Korčák <notifications@github.com>
napsal:

**Comment by jAKErCZ** [comment]
ALe já mám memory limit na 
`php_admin_value[memory_limit] = 2048M`

Takže?

**Comment by jAKErCZ** [comment]
Hotovo opraveno!
Vyhledat: 
`$dom->loadXML($xml);`
Nahradit:
`$dom->loadXML($xml, LIBXML_PARSEHUGE);`

Poté funguje bez problémů...
