### ISSUE TITLE
composer require

### ISSUE THREAD

**Issue by landsman** [martinknor/feed#2]
Ahoj,

přes "composer require makr/feed" se mi stáhla nějaká starší verze, kde ještě chybí Google Merchant.
Nechybí ti propojení s packagist.org? 

díky

**Comment by landsman** [comment]
Ping :)

**Comment by landsman** [comment]
Tak jsem teď na novém projektu přidával feed a zase špatná verze:

"Installing makr/feed (1.0.3)"

Máš to propojené s packagist.org ?

**Comment by martinknor** [comment]
Ano, kdyz se podivas na packagist tak vidis ze tam jsou vsechny verze...

[image: Vložený obrázek 1]
