### ISSUE TITLE
generování s https

### ISSUE THREAD

**Issue by landsman** [martinknor/feed#3]
Na localhostu mi generování funguje korektně, ale na serveru, kde mám https router neustále vrací:

`No route for Catalog:Homepage:item(id=4590, slug=patice-gu10-objimka) `

Což je v pohodě tvar.

Generuji:

`$item->setUrl($this->linkGenerator->link("Catalog:Homepage:item", ["id" => $product->getId(), "slug" => $product->getSlug()]))`

Když v routeru zakomentuji https (`Route::$defaultFlags = Route::SECURED;`), tak se feedy vygenerují korektně.

Napadá tě, co by mohlo být špatně?

**Comment by martinknor** [comment]
Zkusil bych promazat cache? jinak to nema nic spolecneho s rozsirenim

**Comment by landsman** [comment]
No bez https to fungovalo v pořádku. Máš možnost to zkusit?

**Comment by martinknor** [comment]
Mam to prave na vsech serverech pod https a vsude to funguje korektne.
Posli kod kde generujes link a jaky mas router.

**Comment by landsman** [comment]
FeedZboziGenerator.php:

`<?php

namespace App\Model;

use Mk\Feed\Generators\Zbozi\ExtraMessage;
use Mk\Feed\Generators\Zbozi\Generator;
use Mk\Feed\Generators\Zbozi\Item;
use Mk\Feed\Storage;
use Nette\Application\LinkGenerator;
use App\Model\CatalogModel;
use App\Entity\CatalogItem;

class FeedZboziGenerator extends Generator
{
    /** @var CatalogModel */
    private $productRepository;

    /** @var \Nette\Application\LinkGenerator */
    private $linkGenerator;

    /**
     * @param Storage $storage
     * @param \App\Model\CatalogModel $productRepository
     * @param LinkGenerator $linkGenerator
     */
    public function __construct(Storage $storage, CatalogModel $productRepository, LinkGenerator $linkGenerator)
    {
        parent::__construct($storage);

        $this->productRepository = $productRepository;
        $this->linkGenerator = $linkGenerator;
    }

    /**
     * make a feed
     */
    function generate()
    {
        $products = $this->productRepository->DQL_FindAllItems();

        foreach ($products as $item)
        {
            $product = $this->createItem($item[0]);
            $this->addItem($product);
        }
    }

    /***
     * @param CatalogItem $product
     * @return Item
     */
    protected function createItem(CatalogItem $product)
    {
        $item = new Item();
        $item->setProductName($product->getName())   #název nabídky, povinné, doporučená délka 70 znaků
        ->setDescription($product->getMetaDescription()) #popis nabídky, povinné (doporučená délka do 1000 znaků)
        ->setUrl($this->linkGenerator->link("Catalog:Homepage:item", ["id" => $product->getId(), "slug" => $product->getSlug()])) #adresa nabídky v eshopu, povinné
        ->setPriceVat($product->getPriceWithVat()) #cena, povinné; číselná hodnota, max. dvě desetinná místa
        ->setItemId($product->getId()) #identifikátor nabídky v eshopu, nepovinné (alfanumerické znaky)
        ->setEan($product->getEAN()) #kód obchodní položky (čárový kód), nepovinné
        ->setDeliveryDate(0) #dostupnost, povinné (celé číslo nebo datum ve formátu RRRR-MM-DD)
        ->setVisibility(1 == $product->getAvailibility() ? true : false); #zobrazování nabídky na Zboží.cz
        $item->addImage($product->getImage()); #adresa obrázku, nepovinné, doporučujeme uvádět; značku je možné opakovat
        return $item;
    }

}`

RouterFactory.php:

`<?php

namespace App;

use Nette;
use Nette\Application\Routers\RouteList;
use Nette\Application\Routers\Route;
use Kdyby\Doctrine\EntityManager;
use App\Model\CatalogModel;
use App\Model\PageModel;

class RouterFactory
{
	/**
	 * @var EntityManager
	 */
	public $entityManager;
	private $cmsRoutes;

	public function __construct(CatalogModel $catalogModel, PageModel $pageModel)
	{
		$this->cmsRoutes = $pageModel->FindCMSPageUrl();
	}

    /**
     * @return array|RouteList
     */
    private function createCatalogRouter()
    {
        $router = new RouteList('Catalog');

        /** Redirects */
        $router[] = new Route('index.php', 'Homepage:default', Route::ONE_WAY);
        $router[] = new Route('index.html', 'Homepage:default', Route::ONE_WAY);

        $router[] = new Route("kategorie/<id>-<slug>", [
            "presenter" => "Homepage",
            "action" => "category",
            "id" => null,
            "slug" => null
        ]);
        $router[] = new Route("produkt/<id>-<slug>", [
            "presenter" => "Homepage",
            "action" => "item",
            "id" => null,
            "slug" => null
        ]);
        $router[] = new Route("priloha/<id>", [
            "presenter" => "Homepage",
            "action" => "attachment",
            "id" => null
        ]);
        $router[] = new Route("vyrobce/<id>-<slug>", [
            "presenter" => "Homepage",
            "action" => "producer",
            "id" => null,
            "slug" => null
        ]);

        /**
         * Search
         */
        $router[] = new Route("hledat", [
            "presenter" => "Homepage",
            "action" => "search",
        ]);

        /**
         * Cart
         */
        $router[] = new Route("kosik", [
            "presenter" => "Cart",
            "action" => "default",
        ]);
        $router[] = new Route("kosik/objednat", [
            "presenter" => "Cart",
            "action" => "info",
        ]);
        $router[] = new Route("kosik/objednat", [
            "presenter" => "Cart",
            "action" => "info",
        ]);
        $router[] = new Route("kosik/doprava-a-platba", [
            "presenter" => "Cart",
            "action" => "paymentTransfer",
        ]);
        $router[] = new Route("kosik/dokonceni-objednavky", [
            "presenter" => "Cart",
            "action" => "summary",
        ]);
        $router[] = new Route("kosik/dekujeme-za-objednavku", [
            "presenter" => "Cart",
            "action" => "completed",
        ]);
        $router[] = new Route("registrace", [
            "presenter" => "User",
            "action" => "registration",
        ]);
        $router[] = new Route("registrace-uspesna", [
            "presenter" => "User",
            "action" => "registrationSuccessful",
        ]);

        /**
         * CMS pages
         */
        foreach($this->cmsRoutes as $id => $url)
        {
            $router[] = new Route($url, [
                "presenter" => "Page",
                "action" => "default",
                "id" => $id
            ]);
        }
        return $router;
    }

    /**
     * @return Nette\Application\IRouter
     */
    private function createApiRouter()
    {
        $router = new RouteList('API');
        $router[] = new Route("sitemap.xml", "Homepage:sitemap");
        $router[] = new Route("api/fman", "Fman:default");
        $router[] = new Route("api/fman/connector", "Fman:connector");
        $router[] = new Route('api/<presenter>/<action>[/<id>]', [
            "presenter" => "Homepage",
            "action" => "default",
            "id" => null
        ]);

        return $router;
    }

	/**
	 * @return Nette\Application\IRouter
	 */
	public function createRouter()
	{

        Route::$defaultFlags = Route::SECURED; #production
        $router = new RouteList();

        /** Admin */
        $router[] = new Route("admin/<presenter>/<action>[/<id>]", [
            "module" => "Admin",
            "presenter" => "Homepage",
            "action" => "default"
        ]);
        $router[] = new Route("fman", [
            "module" => "Admin",
            "presenter" => "Fman",
            "action" => "default",
        ]);

        /** E-shop */
        $router[] = $this->createCatalogRouter();

        /** API */
        $router[] = $this->createApiRouter();

        /** Homepage */
		$router[] = new Route('<presenter>/<action>[/<id>]', 'Catalog:Homepage:default');

		return $router;
	}

}
`

**Comment by martinknor** [comment]
A mas v Homepage akci item?
