### ISSUE TITLE
Aktualizace na php verzi 7.2

### ISSUE THREAD

**Issue by jAKErCZ** [martinknor/feed#7]
Bylo by možné tento component aktualizovat na php verzi 7.2? Na které běží naše aplikace..

Díky

také aktualizace Kdyby/Console na novější verzi...

use Nette\Obejct; 

aktuální: use \Nette\SmartObject;

**Comment by martinknor** [comment]
Neni problem, staci poslat PR.

**Comment by jAKErCZ** [comment]
Co je PR?
Jinak jsme našli další problém 
`Use getProductName() or add annotation @property for Mk\Feed\Generators\Zbozi\Item::$productName in C:\xampp\htdocs\e-shop\vendor\latte\latte\src\Latte\Engine.php(161) : eval()'d code:16`

**Comment by martinknor** [comment]
PR je pull request, muzete to upravit a ja to pridam do knihovny.

K vasemu problemu, nevim jak to volate, ale asi je potreba volat `$item->getProductName()`, misto `$item->productName`, coz rika i samotna chybova hlaska

**Comment by jAKErCZ** [comment]
Volám to přesně podle vaší dokumentace tedy...

`    function generate()
    {

        $items = [
            $this->createItem(),
            $this->createItem(),
            $this->createItem(),
            $this->createItem(),
        ];

        foreach ($items as $item) {
            $this->addItem($item);
        }
    }`

Problém se týká řádku: ` $this->addItem($item);`

**Comment by martinknor** [comment]
Tohle mi bohuzel nic nereknu, potrebuji vypis cele chyby, idealne cele ladenky. Ale problem bude prave v te metode addItem, kterou si plnite vlastni produkty.

**Comment by jAKErCZ** [comment]
Přikládám screen z laděnky, už se tento problém snažím řešit nějakou dobu a zatím nic. Pokud cokoliv potřeba napište.. Rád aby se to vyřešilo.. 
![fireshot capture 3 - user deprecated_ use getpr_ - http___localhost_e-shop_cli_import_homepage_zbozi](https://user-images.githubusercontent.com/7289889/35805626-e526d1fc-0a7c-11e8-8884-f35d7e6fb542.png)

Funkce **addItem**
```
public function addItem(IItem $item)
    {
        if (!$this->prepared) {
            $this->prepare();
        }

        if (!$item->validate()) {
            throw new ItemIncompletedException('Item is not complete');
        }

        $latte = new Engine;
        $xmlItem = $latte->renderToString($this->getTemplate('item'), array('item' => $item));
        fwrite($this->handle, $xmlItem);
    }
```
